// Tags and tools constants
export const tags =
{
    frontend: 'Frontend',
    backend: 'Backend',
    fullstack: 'Fullstack',
    mobile: 'Mobile',
    web: 'Web',
    desktop: 'Desktop',
    game: 'Game',
    ai: 'AI',
    ml: 'ML',
    dl: 'DL',
    cv: 'CV',
    nlp: 'NLP',
    bigdata: 'Big Data',
    cloud: 'Cloud',
    devops: 'DevOps',
    testing: 'Testing',
    security: 'Security',
    blockchain: 'Blockchain',
    iot: 'IoT',
    ar: 'AR',
    vr: 'VR',
    mr: 'MR',
    robotics: 'Robotics',
}

export const tools =
{
    other: 'Other',
    nodejs: 'Node.js',
    react: 'React',
    angular: 'Angular',
    vue: 'Vue',
    express: 'Express',
    django: 'Django',
    flask: 'Flask',
    laravel: 'Laravel',
    spring: 'Spring',
    flutter: 'Flutter',
    reactnative: 'React Native',
    ionic: 'Ionic',
    electron: 'Electron',
    unity: 'Unity',
    unreal: 'Unreal',
    tensorflow: 'TensorFlow',
    keras: 'Keras',
    pytorch: 'PyTorch',
    opencv: 'OpenCV',
    scikitlearn: 'Scikit-learn',
    pandas: 'Pandas',
    numpy: 'NumPy',
    spark: 'Spark',
    hadoop: 'Hadoop',
    aws: 'AWS',
    azure: 'Azure',
    gcp: 'GCP',
    docker: 'Docker',
    kubernetes: 'Kubernetes',
    jenkins: 'Jenkins',
    gitlab: 'GitLab',
    github: 'GitHub',
    selenium: 'Selenium',
}